# Generated by Django 6.0.7 on 2026-07-23 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('cart_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(db_column='cart_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cart.cart')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.PROTECT, related_name='cart_details', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'cart_detail',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('custom_message', models.CharField(blank=True, max_length=500, null=True)),
                ('cart_detail', models.ForeignKey(db_column='cart_detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cartdetail')),
            ],
            options={
                'db_table': 'cart_item',
            },
        ),
    ]
